DEBUG = False
SECRET_KEY = 'e46b4844151ec754e5ddf52384e3d84106734985906a8b76'
PORT = 5000
POLL_REFRESH_RATE = 2000  # 2 secs

from BargainingExperiment.config.db_settings import SQLALCHEMY_DATABASE_USER, SQLALCHEMY_DATABASE_PASS, SQLALCHEMY_DATABASE_SERVER, SQLALCHEMY_DATABASE_NAME
SQLALCHEMY_DATABASE_URI = 'mysql://{}:{}@{}/{}'.format(SQLALCHEMY_DATABASE_USER, SQLALCHEMY_DATABASE_PASS, SQLALCHEMY_DATABASE_SERVER, SQLALCHEMY_DATABASE_NAME)
SQLALCHEMY_ECHO = DEBUG
SQLALCHEMY_TRACK_MODIFICATIONS = False
