SQLALCHEMY_DATABASE_USER = 'urmeek'
SQLALCHEMY_DATABASE_PASS = 'SoBA123!'
SQLALCHEMY_DATABASE_NAME = 'bargaining'
SQLALCHEMY_DATABASE_SERVER = 'localhost'
SQLALCHEMY_DATABASE_SERVER = 'tokaji.agsmad.ucr.edu'
SQLALCHEMY_DATABASE_URI = 'mysql://{}:{}@{}/{}'.format(SQLALCHEMY_DATABASE_USER, SQLALCHEMY_DATABASE_PASS, SQLALCHEMY_DATABASE_SERVER, SQLALCHEMY_DATABASE_NAME)